image: jeekajoo/planvelo

stages:
  - test
  - deploy

before_script:
- rm -Rf $LOCAL_DIR_TEST $LOCAL_DIR_STAGE $LOCAL_DIR_PROD
- jekyll clean

test:
  stage: test
  script:
  - jekyll build -d $LOCAL_DIR_TEST
  artifacts:
    paths:
    - $LOCAL_DIR_TEST

deploy-stage:
  stage: deploy
  script:
  - jekyll build --config _config.yml,_config_stage.yml --destination $LOCAL_DIR_STAGE
  - lftp -c "set ftp:ssl-allow no; open -u $FTP_USER,$FTP_PASSWORD $FTP_HOST; mirror -Rev --parallel=10 --exclude-glob .git* --exclude .git/ $LOCAL_DIR_STAGE $FTP_REMOTE_DIR_STAGE"
  environment:
    name: stage

deploy-prod:
  stage: deploy
  script:
  - JEKYLL_ENV=production jekyll build --config _config.yml,_config_prod.yml --destination $LOCAL_DIR_PROD
  - lftp -c "set ftp:ssl-allow no; open -u $FTP_USER,$FTP_PASSWORD $FTP_HOST; mirror -Rev --parallel=10 --exclude-glob .git* --exclude .git/ $LOCAL_DIR_PROD $FTP_REMOTE_DIR_PROD"
  when: manual
  environment:
    name: prod
