lang: fr
title: Observatoire du Plan Vélo
logo: /assets/images/logo.png
website: https://parisenselle.fr
website-desc: Paris en Selle
author: parisenselle
description: >
  Avec cet observatoire, l'association Paris en Selle informe les habitants de Paris 
  et d’Île-de-France sur l'avancement des politiques cyclables et l'amélioration des 
  conditions de circulation à vélo dans la capitale.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter:
  username: parisenselle
github:
  username: parisenselle
gitlab:
  username: parisenselle
facebook:
  username: parisenselle
social:
  name: Paris en Selle
  links:
    - https://twitter.com/parisenselle
    - https://www.facebook.com/parisenselle

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/logo-og.png

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-twitter-plugin
  - jekyll-toc
exclude:
  - Gemfile
  - Gemfile.lock
  - .gitlab-ci.yml
  - Dockerfile
  - README.md
  - .tweet-cache
  - doc
