lang: fr
title: Observatoire du plan vélo
logo: logo.png
website: http://www.parisenselle.fr
website-desc: Paris En Selle
author: parisenselle
description: >
  A travers cet observatoire du plan vélo, l'association Paris en Selle souhaite permettre à tous
  d'être tenus informés des avancées du plan vélo voté par la mairie de Paris
  en avril 2015.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter:
  username: parisenselle
github:
  username:  parisenselle
social:
  name: Paris en Selle
  links:
    - https://twitter.com/parisenselle
    - https://www.facebook.com/parisenselle
image:
  twitter: /assets/logo.png
  facebook: /assets/logo.png
  height: 100
  width: 100

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
