lang: fr
title: Observatoire du plan vélo
logo: /assets/images/logo.png
website: http://www.parisenselle.fr
website-desc: Paris En Selle
author: parisenselle
description: >
  À travers cet observatoire, l'association Paris en Selle souhaite permettre à tous
  d'être tenus informés des avancées du plan vélo voté par la mairie de Paris
  en avril 2015.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter:
  username: parisenselle
gitlab:
  username: parisenselle
facebook:
  username: parisenselle
social:
  name: Paris en Selle
  links:
    - https://twitter.com/parisenselle
    - https://www.facebook.com/parisenselle

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/logo.png

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-twitter-plugin
exclude:
  - Gemfile
  - Gemfile.lock
  - .gitlab-ci.yml
  - Dockerfile
  - README.md
  - .tweet-cache
  - doc
